
px:
  datasource:
    dataSource:
      type: com.alibaba.druid.pool.DruidDataSource 
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.148.69.148:3306/pi6000
      username: root
      password: root
      initialSize: 5
      maxActive: 20
      
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
