server:
  port: 8081
  contextPath: /pi6000-task-web
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 3600

debug: false
#server.jsp-servlet.init-parameters.development: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: false

spring:
  application:
    name: pi6000-task-web
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  redis:
    host: localhost
    port: 6379
  session:
    #REDIS使用redis作为会话存储、NONE则使用中间件的会话，用户登录信息使用EHcache存储,默认为EHcache存储
    storeType: NONE
    
px:
  datasource:
    dataSource:
      type: com.alibaba.druid.pool.DruidDataSource 
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.42.155:3306/pi6000
      username: root
      password: root
      initialSize: 5
      maxActive: 20

  ua:
    appID: 1ae211c543a14cf6981274fec3281f0c
    loginMode: parallel         #登录策略(kickout/single/parallel)
    maxCaptchaCount: 1        #用户和密码输入错误几次，出现验证码(若设为为0，表示默认显示验证码)
    maxCaptchaTime: 1 
    maxSession: 50
    #1、sso（PI6000 单点登录）; 2、workbench
    authMode: sso
    #是否启用方法注解权限校验
    methodAuthz:
      enabled: true
    auth:
      #是否启用登录认证和权限校验
      enabled: true
      loginURL: /td-console/login.html
      successURL: /td-tdmgr/index.jsp
      unauthURL: /errorpages/401.htm
      
      #url权限校验拦截器，采用短路拦截规则，优先级: annoAutzPath->annoAutzPath->urlAutzPath
      #匿名认证拦截器
      annoAutzPath:                
        - /td-console/login.html
        - /errorpages/401.htm
        - /**/*.htm
        - /**/*.html
        - /api/**
        - /hessian/**
      #登录认证拦截器
      loginAutzPath:                
        - /td-tdmgr/index.jsp
        - /td-tasktree/tasktree.jsp
        - /test.jsp
        - /td-tectree/tectree.jsp
        - /
      #菜单URL和功能认下拦截器
      urlAutzPath:                  
        - /**
    sso:
      ssoServer: http://192.168.99.100:8080/pi6000-ua-sso        #单点登录服务地址，建议配置成网关单点登录地址
