server:
  port: 8080
  contextPath: /pi6000-ua-sso
  tomcat:
    uri-encoding: UTF-8
    
#eureka.instance.hostName: uasso
  
spring:
  application:
    name: pi6000-ua-sso
  redis:
    database: 1

tableSchema: 

px:
  sso:
    sql:
      validateUser: select user_pwd,user_id from ${tableSchema}pt_ua_user where user_name =? and user_status=1
      loginLog: insert into ${tableSchema}pt_ua_userlogin (userlogin_id,userlogin_userid, userlogin_sessionid, userlogin_name,userlogin_ip,userlogin_stime,userlogin_appid)values(?,?,?,?,?,?,?)
      logoutLog: update ${tableSchema}pt_ua_userlogin set userlogin_etime = ? where userlogin_sessionid=?
    st:
      timeToKillInSeconds: 1000
    tgt:
      maxTimeToLiveInSeconds: 28800
      timeToKillInSeconds: 7200
       
    
