server:
  port: 8082
  contextPath: /pi6000-ua-web
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: pi6000-ua-web
    
px:
  ua:
    #同步isc组织机构的Restful服务的url
    iscAdapterUrl: http://172.16.200.31:7002/isc_frontmv_serv
    #长期未登录用户审计时间（单位：天）
    unloginTime: 180
    appID: 1ae211c543a14cf6981274fec3281f0c
    loginMode: parallel         #登录策略(kickout/single/parallel)
    maxCaptchaCount: 3        #用户和密码输入错误几次，出现验证码(若设为为0，表示默认显示验证码)
    maxCaptchaTime: 1 
    maxSession: 50
    #1、isc_sso(ISC认证，PI6000 鉴权); 2、sso（PI6000 单点登录）; 3、workbench
    authMode: sso
    #是否启用方法注解权限校验
    methodAuthz.enabled: true
    auth:
      #是否启用登录认证和权限校验
      enabled: false
      loginURL: /ua-console/login.html
      successURL: /ua-mgr/index.jsp
      unauthURL: /errorpages/401.htm
      
      #url权限校验拦截器，采用短路拦截规则，优先级: annoAutzPath->annoAutzPath->urlAutzPath
      #匿名认证拦截器
      annoAutzPath:
        - /errorpages/401.htm
        - /**/*.htm
        - /**/*.html
        - /hessian/**
        - /api/ua/auth/**
      #登录认证拦截器
      loginAutzPath:     
        - /ua-mgr/index.jsp
        - /ua-welcome/welcome.jsp
        - /ua-roleentrust/roleentrust.jsp
        - /ua-menutree/menutree.jsp
        - /ua-functree/functree.jsp
        - /ua-usertree/usertree.jsp
        - /ua-approletree/approletree.jsp
        - /ua-orgroletree/orgroletree.jsp
        - /ua-service/service.jsp
        - /api/**
        - /
      #菜单URL和功能认下拦截器
      urlAutzPath:           
        - /**
    sso:
      ssoServer: http://192.168.99.100/pi6000-ua-sso        #单点登录服务地址，建议配置成网关单点登录地址
