server:
  port: 8081
  contextPath: /pi6000-task-web
  tomcat:
    uri-encoding: UTF-8

debug: false
#server.jsp-servlet.init-parameters.development: true

eureka.instance.hostName: task

spring:
  application:
    name: pi6000-task-web
    
px:
  ua:
    appID: 1ae211c543a14cf6981274fec3281f0c
    loginMode: parallel         #登录策略(kickout/single/parallel)
    maxCaptchaCount: 1        #用户和密码输入错误几次，出现验证码(若设为为0，表示默认显示验证码)
    maxCaptchaTime: 1 
    maxSession: 50
    #1、sso（PI6000 单点登录）; 2、workbench
    authMode: sso
    #是否启用方法注解权限校验
    methodAuthz:
      enabled: true
    auth:
      #是否启用登录认证和权限校验
      enabled: false
      loginURL: /td-console/login.html
      successURL: /td-tdmgr/index.jsp
      unauthURL: /errorpages/401.htm
      
      #url权限校验拦截器，采用短路拦截规则，优先级: annoAutzPath->annoAutzPath->urlAutzPath
      #匿名认证拦截器
      annoAutzPath:                
        - /td-console/login.html
        - /errorpages/401.htm
        - /**/*.htm
        - /**/*.html
        - /api/**
        - /hessian/**
      #登录认证拦截器
      loginAutzPath:                
        - /td-tdmgr/index.jsp
        - /td-tasktree/tasktree.jsp
        - /test.jsp
        - /td-tectree/tectree.jsp
        - /
      #菜单URL和功能认下拦截器
      urlAutzPath:                  
        - /**
    sso:
      ssoServer: http://192.168.99.100/pi6000-ua-sso        #单点登录服务地址，建议配置成网关单点登录地址
